config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :kittens
  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :cuteness, :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten successfully created."
      redirect_to @kitten
    else
      flash.now[:warning] = "Something went wrong. Please try again."
      render :new
    end
  end

  def edit
  end

  def update
    if @kitten.update(kitten_params)
      flash[:success] = "Kitten successfully updated."
      redirect_to @kitten
    else
      render :edit
    end
  end

  def destroy
    @kitten.destroy
    flash[:success] = "Kitten destroyed :-("
    redirect_to root_url
  end

  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten_form.html.erb
<%= form_with(model: @kitten) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "A cute name" %>

  <%= f.label :age, "Age in Months" %>
  <%= f.number_field :age, in: 1..12%>

  <%= f.label :cutness %>
  <%= f.range_field :cuteness, in: 1..10, step: 1 %>

  <%= f.label :softness %>
  <%= f.range_field :softness, in: 1..10, step: 1 %>

  <%= f.submit "Submit" %>
<% end %>

app/views/kittens/_kitten_info.html.erb
<ul>
  <li>Name: <%= @kitten.name %></li>
  <li>Age: <%= pluralize(@kitten.age, 'month') %></li>
  <li>Cuteness: <%= @kitten.cuteness %>/10</li>
  <li>Softness: <%= @kitten.softness %>/10</li>
</ul>

app/views/kittens/edit.html.erb
<%= render 'kitten_form' %>

<%= link_to "home", root_url %>
<%= link_to "delete #{@kitten.name}", @kitten, method: :delete, data: { confirm: "Are you sure?" } %>

app/views/kittens/index.html.erb
<ol>
  <% @kittens.each do |kitten| %>
    <li><%= link_to kitten.name, kitten %> | <%= link_to "delete", kitten, method: :delete %></li>
  <% end %>
</ol>

app/views/kittens/new.html.erb
<%= render 'kitten_form' %>

app/views/kittens/show.html.erb
<%= render 'kitten_info' %>

<%= link_to "home", root_url %>
<%= link_to "edit", edit_kitten_path(@kitten) %>
<%= link_to "delete", @kitten, method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:p, message, class: message_type) %>
    <% end %>
    <%= yield %>
  </body>
</html>